# Site settings
title: 静波时光
header-img: img/home-bg.jpg
email: jingbolee@foxmail.com
copyright_name: Your/Project/Corporate Name
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/"
url: "http://www.lijingbo.cc"
github_username:  jingbolee
email_username:  jingbolee@foxmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
